language: node_js
branches:
    only:
    - master
services:
- docker
node_js:
- '10.7'
after_success:
- make
- make deploy
env:
  global:
  - secure: EeJh+PhXsqWZxtLPTE5TUGi2WkxfpC+yv30qVhMAitEW4VMy2BxRX/Vw4UpX9KsHZjzHzMM7h9PfWTfHg+ZlBjU8NLWAOcuHBRGfWNFI6UZu1OFC1TgOIwb7sEFFPpvFy75qREbIfl1MpaFJwR5jZ+h1B59TMHHRmW1gB2mp84O+YLdXelg8yHgIkFE+gkhxYN2UCzGUyfkUKFMwBPXQubyISv9pi4+kM7/WMS15aXXe3Us68iOKxhdZBZXiZ8CQmTDSYlewOmvx+6PWw5BbvM5v0k6BJObFtAt8qIhXwJFKlBsZfZS9JuHkoT5Bvb3ZQ7Xqu10GkPE/bcZwlwJJK4fHtKRR2t7lhl6eajOTQeoyE3gJ4LNmGMSy2wnMAm2jHk+x39EnKEL1i/2ASWNu9JwId7KoOnVkluTBEJI989q7x/PFZTRMmXLfppc+KZEkwV6f0yBPt/rJV7J6N5uvAOkP35tjQ1Ahx2aHyFdGsOZNntQFv/UELqpGvQnVMKjNSKXEFqbyI2lt/MXfmhjFMOK5bvN2gfgRl7DfWS6jHiM13Tbpabc+MVbXftW8vIZBteNJ0AtnJPjaX3XVx6MbqoA8e/8NsgbKnbpXHfPjFW0Wy+MN9We/KrO8tXkHYcTX1nz7t5wPkwmWRLlNE1w4LeZUXqiXielMFWy11ErKRDs=
  - secure: mlPAe4ZhvkyG7IapKtQvzm8NuJOifvpG0Ajcyg/rQGHxW+7m8me5CGJXLgyap/sz+oca54qiO+a96wABzzTWaxvOWIpc9oW6oJPcTPjte+gJpGCVF3GCuRBwiBFY/a0HBlzswyt9Ds6pSsSoWD4UhvFBsyhxy0WYR4zCIoOnMXq2LqyYsXfigh9/O1djl5+1MYQU6tTsiyiEVq6AC+oLwSS1Kxyp88WgHCTBOasnjPgHHAfZU+vSemdWZhgIG2GHqHBK/GY25PPn+WBEYPxoCxUTbxjxrEfD+RbUzOFVIfdKil6j0TwybXx48ajVsTGOcdpwDIe6BArWjvmQXy4LAElI1hEjrOttRQa5Ip4JL8QZ5zBzZXN6EmnxyQ6VUSRvK0b7a+TDOYcyl8+n35Mgg3IJiYdEsd51Oq19RKwftlhKyejP4YMyp5RAscqjHKmf3wfTqdQa2mDOZh3dbqcfpt/461IAj4h2M2rx9rZ7RYZcNx0IdLFfniS9yH3bMvVSoU7yzEWjmj5Np9HO5almm1xWzWHIGfz+C1gWexugdCCXL6eeAyP9MENISaYmoUtSvt3bNT9+/HVQOB8algii2KK/kwWO8QpXkIJSFO1wyHhJjx82ATCn1QSGBTXRqVnQGcYlPvHHjxFiAP0G+zqYLesOVavpajur99bMmRgz6c8=
before_install:
- docker login -u="ashwinath" -p="$DOCKER_PASSWORD"
- openssl aes-256-cbc -K $encrypted_a5d544b25f4c_key -iv $encrypted_a5d544b25f4c_iv -in travis_rsa.enc -out /tmp/travis_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/travis_rsa
- ssh-add /tmp/travis_rsa
