const CURRENCY_STACK_SIZE = {
  "Divine Orb": 10,
  "Portal Scroll": 40,
  "Exalted Orb": 10,
  "Ancient Orb": 20,
  "Orb of Scouring": 30,
  "Orb of Binding": 20,
  "Splinter of Tul": 100,
  "Blacksmith's Whetstone": 20,
  "Armourer's Scrap": 40,
  "Orb of Transmutation": 40,
  "Orb of Horizons": 20,
  "Blessing of Xoph": 10,
  "Engineer's Orb": 20,
  "Splinter of Chayula": 100,
  "Gemcutter's Prism": 20,
  "Splinter of Xoph": 100,
  "Cartographer's Chisel": 20,
  "Blessed Orb": 20,
  "Jeweller's Orb": 20,
  "Orb of Alteration": 20,
  "Orb of Augmentation": 30,
  "Mirror of Kalandra": 10,
  "Blessing of Chayula": 10,
  "Master Cartographer's Sextant": 10,
  "Blessing of Esh": 10,
  "Journeyman Cartographer's Sextant": 10,
  "Blessing of Tul": 10,
  "Regal Orb": 10,
  "Orb of Fusing": 20,
  "Splinter of Esh": 100,
  "Orb of Chance": 20,
  "Perandus Coin": 1000,
  "Scroll of Wisdom": 40,
  "Mirror Shard": 20,
  "Harbinger's Orb": 20,
  "Orb of Annulment": 20,
  "Blessing of Uul-Netol": 10,
  "Exalted Shard": 20,
  "Vaal Orb": 10,
  "Apprentice Cartographer's Sextant": 10,
  "Orb of Regret": 40,
  "Orb of Alchemy": 10,
  "Silver Coin": 30,
  "Splinter of Uul-Netol": 100,
  "Glassblower's Bauble": 20,
  "Chromatic Orb": 20,
}

const LEAGUE = "Betrayal";

export {
    LEAGUE,
    CURRENCY_STACK_SIZE,
};
